name: label-syncer

on:
  workflow_dispatch:

permissions: read-all

jobs:
  label-syncer:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0

      - name: run sync-labels
        uses: docker://ghcr.io/cpanato/github-label-syncer:0.2.0
        env:
          POLICY_NAME: "sync-labels-2"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
